# Generated by Django 3.1.2 on 2020-10-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sherbimet',
            new_name='Sherbime',
        ),
    ]
