# Generated by Django 3.1.2 on 2020-10-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemi', '0002_auto_20201017_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partneret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=',media/')),
            ],
        ),
    ]
