# Generated by Django 3.1.2 on 2020-10-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemi', '0003_partneret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projektet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media/')),
                ('tittle', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='partneret',
            name='images',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
