# Generated by Django 3.1.2 on 2020-10-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemi', '0004_auto_20201017_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rrethnesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000)),
                ('text1', models.TextField(max_length=10000)),
                ('images', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
