# Generated by Django 3.1.2 on 2020-10-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemi', '0005_rrethnesh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=6000)),
                ('adresa', models.CharField(max_length=60)),
                ('cel', models.CharField(max_length=20)),
                ('cel1', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('map', models.URLField(max_length=1000)),
            ],
        ),
    ]
