# Generated by Django 3.1.2 on 2020-10-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemi', '0006_kontakt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sherbimet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=1000)),
                ('list1', models.CharField(max_length=500)),
                ('list2', models.CharField(max_length=500)),
                ('list3', models.CharField(max_length=500)),
                ('list4', models.CharField(max_length=500)),
                ('list5', models.CharField(max_length=500)),
                ('list6', models.CharField(max_length=500)),
                ('list7', models.CharField(max_length=500)),
                ('list8', models.CharField(max_length=500)),
                ('list9', models.CharField(max_length=500)),
                ('list10', models.CharField(max_length=500)),
                ('list11', models.CharField(max_length=500)),
                ('list12', models.CharField(max_length=500)),
                ('list13', models.CharField(max_length=500)),
                ('list14', models.CharField(max_length=500)),
                ('list15', models.CharField(max_length=500)),
                ('images', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Sherbime',
            new_name='Home',
        ),
    ]
